export const data = {
  bio: {
    name: "Ankit Kumar",
    tagline: "Fullstack Mobile Developer",
    email: "ankitdroiddeveloper@gmail.com",
    github: "https://github.com/AnkitDroidGit",
    website: "https://ankitdroidgit.github.io/",
    linkedin: "https://linkedin.com/in/kumarankitkumar",
  },
  skills: [
    "Java",
    "Kotlin",
    "Dart",
    "Swift",
    "C/C++",
    "Python",
    "JavaScript (ES6)",
    "TypeScript",
    "SQL",
    "Nodejs",
    "React",
    "Bootstrap",
    "Express",
    "MongoDB",
    "Behave",
    "Jest",
    "Git",
    "Github",
    "MySQL",
    "NPM",
    "Android",
    "iOS",
    "Flutter",
    "React Native",
  ],
};
