export const data = {
  bio: {
    name: "Ankit Kumar",
    tagline: "Fullstack Mobile Developer",
    email: "ankitdroiddeveloper@gmail.com",
    github: "https://github.com/AnkitDroidGit",
    website: "https://ankitdroidgit.github.io/",
    linkedin: "https://linkedin.com/in/kumarankitkumar",
    objective:
      "Curious. persistent and solution oriented, A self-motivated and highly enthusiastic individual. Able to work on own initiative individually and as a part of a team. Proven leadership skills involving management, developing and motivating teams",
  },
  skills: [
    "Java",
    "Kotlin",
    "Dart",
    "Swift",
    "C/C++",
    "Python",
    "JavaScript (ES6)",
    "TypeScript",
    "SQL",
    "Nodejs",
    "React",
    "Bootstrap",
    "Express",
    "MongoDB",
    "Behave",
    "Jest",
    "Git",
    "Github",
    "MySQL",
    "NPM",
    "Android",
    "iOS",
    "Flutter",
    "React Native",
  ],
  positions: [
    {
      id: "1",
      title: "Senior Fullstack Developer",
      company: "Rea Group",
      startDate: "2019-09-17",
      endDate: null,
      employmentType: "FULL TIME",
      location: "Kuala Lumpur, Malaysia",
      achievements: [
        "Building a large Node.js serverless application powering iProperty.com.my mobile apps+ GraphQL API",
        "Mentoring developers, running workshops to upskilling team, finding training opportunities on backend stuffs",
        "Development of Node.js + GraphQL and React Native applications, working with GraphQL, AWS, New Relic, Typescript, etc",
        "Creating and deploying serverless functions",
        "Help to improve processes using agile methodologies which improve overall productivity and quality",
        "Responsible for designing, implementing and maintaining our mobile development and set standards and best practices",
        "Mentoring team through discussions, design reviews and technical presentations in a collaborative environment",
        "Working with multicultural teams in Melbourne, Hong Kong, Indonesia, Singapore, China, under the umbrella of the REA Group",
        "Display highly developed skills in modern software development techniques such as Object-oriented programming, Test Driven development,Micro- services and continuous delivery",
        "Work as trusted advisor to product, design and other key stakeholders",
        "Take a lead on initiatives and features",
        "Participate in discoveries and inceptions activities",
      ],
    },
    {
      id: "2",
      title: "Middleware Engineer",
      company: "Capital Platforms",
      startDate: "2018-06-01",
      endDate: "2019-09-01",
      employmentType: "FULL_TIME",
      location: "Kuala Lumpur, Malaysia",
      achievements: [
        "Building native mobile applications, both, Android and iOS, for Capital Plaforms Pvt Ltd",
        "Working with Android, Kotlin, iOS, Swift, Firebase, and .NET to build interactive movile applications",
        "Leading mobile team, code review, selecting technology stack, tech spikes, implementation of major features",
        "Designing, coding, testing and deploying software products using a wide range of technologies and platforms",
        "Quarterly check system health w.r.t operation, architecture, development",
        "Help to improve processes using agile methodologies which improve overall productivity and quality",
        "Responsible for designing, implementing and maintaining our mobile development and set standards and best practices",
        "Mentoring team through discussions, design reviews and technical presentations in a collaborative environment",
        "Display highly developed skills in modern software development techniques such as Object-oriented programming, Test Driven development,Micro- services and continuous delivery",
        "Work as trusted advisor to product, design and other key stakeholders",
        "Take a lead on initiatives and features",
        "Participate in discoveries and inceptions activities",
      ],
    },
    {
      id: "3",
      title: "Senior Mobile Application Developer",
      company: "Maybank Berhad",
      startDate: "2017-01-01",
      endDate: "2018-06-01",
      employmentType: "FULL TIME",
      location: "Kuala Lumpur, Malaysia",
      achievements: [
        "Building native mobile applications, both, Android and iOS, for Maybank Investment Bank",
        "Working with Android, Kotlin, Java, iOS, Swift, Firebase, interactive movile applications",
        "Leading mobile team, code review, selecting technology stack, tech spikes, implementation of major features",
        "Designing, coding, testing and deploying software products using a wide range of technologies and platforms",
        "Quarterly check system health w.r.t operation, architecture, development",
        "Help to improve processes using agile methodologies which improve overall productivity and quality",
        "Responsible for designing, implementing and maintaining our mobile development and set standards and best practices",
        "Mentoring team through discussions, design reviews and technical presentations in a collaborative environment",
        "Display highly developed skills in modern software development techniques such as Object-oriented programming, Test Driven development,Micro- services and continuous delivery",
        "Work as trusted advisor to product, design and other key stakeholders",
        "Take a lead on initiatives and features",
        "Participate in discoveries and inceptions activities",
      ],
    },
    {
      id: "4",
      title: "Lead Sofware Enginner - Android",
      company: "Parken Solution",
      startDate: "2015-10-01",
      endDate: "2016-12-01",
      employmentType: "FULL TIME",
      location: "Jaipur, India",
      achievements: [
        "Leading android mobile team, code review, selecting technology stack, tech spikes, implementation of major features",
        "Designing, coding, testing and deploying software products using a wide range of technologies and platforms",
        "Quarterly check system health w.r.t operation, architecture, development",
        "Help to improve processes using agile methodologies which improve overall productivity and quality",
        "Responsible for designing, implementing and maintaining our mobile development and set standards and best practices",
        "Mentoring team through discussions, design reviews and technical presentations in a collaborative environment",
        "Display highly developed skills in modern software development techniques such as Object-oriented programming, Test Driven development,Micro- services and continuous delivery",
        "Work as trusted advisor to product, design and other key stakeholders",
        "Take a lead on initiatives and features",
        "Participate in discoveries and inceptions activities",
      ],
    },
    {
      id: "5",
      title: "Senior Software Engineer - Android",
      company: "Interaction One Solutions",
      startDate: "2014-11-01",
      endDate: "2015-11-01",
      employmentType: "FULL TIME",
      location: "Bangalore, India",
      achievements: [
        "I work with sports data. Processing incoming data feeds, building admin management systems and APIs which are consumed by iOS, Android, and Web clients. Technologies involved are Ruby on Rails, Python and MySQL.",
      ],
    },
  ],
};
